

import javax.swing.*;

import java.awt.*;
import java.awt.event.*;


/**
 * The  GamePanel class represents the main drawing surface and game loop
 * for the platform. It handles rendering the Level and  Player.
 * 
 *  Keyboard input is currently handled by another component class, so the
 * KeyListener implementation is commented out for now.
 * 
 * This class uses a Swing  Timer to update and repaint the screen
 * approximately 60 times per second.
 * 
 * @author Evie Hipwood 
 * See CSSE220 Final Project Document to see resources used
 */
public class GamePanel extends JPanel implements ActionListener{ //KeyListener is in Component now
    private Timer timer;
    private Player player;
    private Level level;
    //private boolean leftPressed, rightPressed;

    
    /**
     * Constructs a new  GamePanel, initializes the level and player,
     * and starts the update timer.
     */
    public GamePanel() {
        setPreferredSize(new Dimension(800, 600));
        setBackground(Color.WHITE);

        
        level = new Level(1);
        
        timer = new Timer(16, this);
        timer.start();

        //addKeyListener(this);
        setFocusable(true);
        requestFocusInWindow();
    }

    /**
     * Called automatically by the Swing timer every frame.
     * Updates player logic and triggers a repaint.
     *
     * @param e the ActionEvent generated by the timer
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        //if (leftPressed) player.moveLeft();
        //if (rightPressed) player.moveRight();
       // player.update(level); 
        
    	repaint();
    }

    /**
     * Draws the current level and player on the panel.
     *
     * @param g the  Graphics context for rendering
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        level.levelDraw(g2);
        player.draw(g2);
    }
    /**
     *  KeyListener methods (currently disabled0 in Component instead. 
    @Override
    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();

        if (key == KeyEvent.VK_LEFT || key == KeyEvent.VK_A) leftPressed = true;
        if (key == KeyEvent.VK_RIGHT || key == KeyEvent.VK_D) rightPressed = true;
        if (key == KeyEvent.VK_SPACE || key == KeyEvent.VK_UP) player.jump();
    }

    @Override
    public void keyReleased(KeyEvent e) {
        int key = e.getKeyCode();

        if (key == KeyEvent.VK_LEFT || key == KeyEvent.VK_A) leftPressed = false;
        if (key == KeyEvent.VK_RIGHT || key == KeyEvent.VK_D) rightPressed = false;
    }

    @Override public void keyTyped(KeyEvent e) {}
    */
}
